flat_data_benthos.Rmd:
  path: dev/flat_data_benthos.Rmd
  state: active
  R: R/gg_map_parametre_data_benthos.R
  tests: tests/testthat/test-gg_map_parametre_data_benthos.R
  vignettes: []
  inflate:
    flat_file: dev/flat_data_benthos.Rmd
    vignette_name: ~
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_data_contamination.Rmd:
  path: dev/flat_data_contamination.Rmd
  state: active
  R:
  - R/get_general_evaluation.R
  - R/get_general_levels.R
  - R/get_kruskal_periods_results.R
  - R/get_last_trend_info.R
  - R/gg_map_data_contamination_rocchmv.R
  - R/spearman_test.R
  tests:
  - tests/testthat/test-gg_map_data_contamination_rocchmv.R
  - tests/testthat/test-spearman_test.R
  - tests/testthat/test-get_last_trend_info.R
  - tests/testthat/test-get_kruskal_periods_results.R
  - tests/testthat/test-get_general_levels.R
  - tests/testthat/test-get_general_evaluation.R
  vignettes: []
  inflate:
    flat_file: dev/flat_data_contamination.Rmd
    vignette_name: ~
    open_vignette: true
    check: false
    document: false
    overwrite: ask
    clean: ask
    codecov: false
flat_fct_build_and_save_basemap.Rmd:
  path: dev/flat_fct_build_and_save_basemap.Rmd
  state: active
  R:
  - R/fct_build_and_save_basemap.R
  - R/load_estuary_basemap.R
  - R/plot_estuary_map.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_fct_build_and_save_basemap.Rmd
    vignette_name: ~
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_utils.Rmd:
  path: dev/flat_utils.Rmd
  state: active
  R:
  - R/ggplot2_colors.R
  - R/make_points_sf.R
  tests: tests/testthat/test-ggplot2_colors.R
  vignettes: []
  inflate:
    flat_file: dev/flat_utils.Rmd
    vignette_name: ~
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
